# Spring properties
spring:
  application:
     name: products-service  # Service registers under this name
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/products-server/templates/    # Trailing / mandatory
                             # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.registry.url}
  instance:
    preferIpAddress: true

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port